{{- $fullName := include "application.fullname" . -}}
{{- $nameSpace := .Release.Namespace -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  namespace: {{ $nameSpace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
          {{- with .Values.environments }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end}}
